### ISSUE TITLE
Cannot find module 'Core', 'Components', 'tag'. Doesn't work on CLI

### ISSUE THREAD

**Issue by smartHasmukh** [Gbuomprisco/ng2-tag-input#431] opened 2017-06-05 08:34 UTC
Got the same error, also using angular/*: ^4.0.0, ng2-tag-input: "^1.3.2"

![erro](https://cloud.githubusercontent.com/assets/8941195/26751769/19803ad2-485f-11e7-8330-3e395456d2ba.png)

`{
  "name": "scroll-down",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-useful-swiper": "^4.0.5",
    "core-js": "^2.4.1",
    "ng2-fullpage": "^2.1.0",
    "ng2-owl-carousel": "^0.1.15",
    "ng2-tag-input": "^1.2.9",
    "primeng": "^4.0.3",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.2",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "^2.0.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
`

**Comment by Gbuomprisco** [comment] 2017-06-05 08:38
@smartHasmukh try 1.3.3?

**Comment by smartHasmukh** [comment] 2017-06-05 09:13
Sure @Gbuomprisco. After install will let you know

**Comment by smartHasmukh** [comment] 2017-06-05 10:02
@Gbuomprisco  I have tired '"ng2-tag-input": "^1.3.3"' but It doesn't working.

![error](https://cloud.githubusercontent.com/assets/8941195/26779697/10e65d74-4a04-11e7-874e-afce38ed1174.png)

**Comment by Gbuomprisco** [comment] 2017-06-05 11:09
Sorry, just tried with 1.3.3 and cli and cannot reproduce that. Maybe delete ng2-tag-input, reinstall, and restart the server.

**Comment by smartHasmukh** [comment] 2017-06-05 11:38
Please have a look my package.json file. Still getting error.    ` "@angular/cli": "1.0.2"` I am using version

```
{
  "name": "scroll-down",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-tag-input": "^1.2.3",
    "angular2-useful-swiper": "^4.0.5",
    "core-js": "^2.4.1",
    "ng2-fullpage": "^2.1.0",
    "ng2-owl-carousel": "^0.1.15",
    "ng2-tag-input": "^1.3.3",
    "primeng": "^4.0.3",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.2",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "^2.0.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}

```

**Comment by Gbuomprisco** [comment] 2017-06-05 11:45
@smartHasmukh the only missing thing I see here is the animations module (@angular/animations). Other than it seems OK. Have you also imported BrowserAnimationsModule?

**Comment by smartHasmukh** [comment] 2017-06-05 12:13
I have installed - BrowserAnimationsModule. but getting same.

**Comment by Gbuomprisco** [comment] 2017-06-05 12:29
@smartHasmukh Post some of the code - impossible to help otherwise. Closing ticket as it's not related to the previous one

**Closed** 2017-06-05 12:32 UTC

**Comment by smartHasmukh** [comment] 2017-06-06 05:21
@Gbuomprisco  Working Fine Thanks!!!

![working](https://cloud.githubusercontent.com/assets/8941195/26814819/fe89d0b4-4aa5-11e7-829e-b795dd029625.png)

**Comment by Gbuomprisco** [comment] 2017-06-06 09:19
Great - what did you do to make it work in the end?

**Comment by smartHasmukh** [comment] 2017-06-06 09:35
I have created new angular 4 project then installed ng2-tag-input module and animation module as well. That's it

**Comment by Gbuomprisco** [comment] 2017-06-06 10:14
great - may help others if they stumble on the same :)

**Comment by smartHasmukh** [comment] 2017-06-06 10:31
Ok Thanks @Gbuomprisco
