### ISSUE TITLE
AoT complains about private properties in the components 

### ISSUE THREAD

**Issue by khuang-va** [Gbuomprisco/ng2-tag-input#224] opened 2017-03-03 15:26 UTC
I got a lot of angular2 compiler errors talking about accessing private properties.
```
src/static/js/app/ngfactory/node_modules/ng2-tag-input/dist/modules/components/tag-input.ngfactory.ts (215,20): Property 'inputId' is private and only accessible within class 'TagInputComponent'.)
src/static/js/app/ngfactory/node_modules/ng2-tag-input/dist/modules/components/tag-input.ngfactory.ts (222,20): Property 'inputClass' is private and only accessible within class 'TagInputComponent'.)
src/static/js/app/ngfactory/node_modules/ng2-tag-input/dist/modules/components/tag-input.ngfactory.ts (229,20): Property 'clearOnBlur' is private and only accessible within class 'TagInputComponent'.)
.....
```

It seems some elements in component template are binding to private methods, which violates 
`Inputs, Outputs, View or Content Child(ren), Hostbindings, and any field you use from the template or annotate for Angular should be public.`

screenshot:
![image](https://cloud.githubusercontent.com/assets/19170625/23556901/c1644a2c-fff3-11e6-8bbf-04416df7185f.png)

In addition, in `TagInputComponent`, it's missing `handleKeyPress()` method, which is binding to `tag-input-form`

**Comment by Gbuomprisco** [comment] 2017-03-04 11:05
Hi @khuang-va,

Thanks for reporting. Could you check version 0.8.8? Thanks!

**Comment by ManojlovicMilos** [comment] 2017-03-05 00:16
Still not working.
I too had same problem. Was in a bit of a rush so I hotfixed it ng2-tag-input-fix fork (very fast, very dirty).
But I'd prefer it fixed on this package.

Thanks.

**Comment by khuang-va** [comment] 2017-03-06 16:45
Hey @Gbuomprisco,

Thank you for your reply. I still got some private property errors.

![image](https://cloud.githubusercontent.com/assets/19170625/23619671/0125d4ec-025a-11e7-83d8-88d66b1691cf.png)

**Comment by Gbuomprisco** [comment] 2017-03-09 11:49
Hi guys,

this was fixed by a contributor. Can you still reproduce? Thanks

**Comment by ManojlovicMilos** [comment] 2017-03-09 14:52
I still get errors because of ng2-material-dropdown dependency.
![image](https://cloud.githubusercontent.com/assets/21346598/23755356/60a3f5d8-04e0-11e7-86e8-d92fa3edb925.png)

**Comment by Gbuomprisco** [comment] 2017-03-09 15:12
This should hopefully fix it https://github.com/Gbuomprisco/ng2-tag-input/pull/237

**Comment by Gbuomprisco** [comment] 2017-03-09 15:39
Published. Fingers crossed now!

**Comment by ManojlovicMilos** [comment] 2017-03-09 18:22
Hi, thanks for quick action and reply.

There is still one more issue:
Property 'scrollListener' is private and only accessible within class 'TagInputDropdown'

**Comment by ManojlovicMilos** [comment] 2017-03-09 18:26
It appears that problem is from ng2-tag-input
From tag-input-dropdown.component.ts file:
private scrollListener(): void{ ..

**Comment by khuang-va** [comment] 2017-03-11 06:21
```
/src/static/js/app/ngfactory/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.ngfactory.ts (160,48): Property 'scrollListener' is private and only accessible within class 'TagInputDropdown'.)
```
This is the only thing complaining by compiler now. 😆

**Comment by ManojlovicMilos** [comment] 2017-03-12 16:05
It works perfectly now 👍

**Closed** 2017-03-12 16:08 UTC
Labels: bug
