### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by avatsaev** [Gbuomprisco/ng2-tag-input#220] opened 2017-02-26 21:44 UTC
Getting this error at compile time with latest Angular CLI (rc.0)

> ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 5:22 in the original .ts file), resolving symbol Ng2DropdownModule in /Users/avatsaev/DEV/ummah/WEB/frontend/admin.ummah-books.com.ng/node_modules/ng2-tag-input/dist/node_modules/ng2-material-dropdown/index.d.ts, resolving symbol TagInputModule in /Users/avatsaev/DEV/ummah/WEB/frontend/admin.ummah-books.com.ng/node_modules/ng2-tag-input/dist/modules/ng2-tag-input.module.d.ts, resolving symbol TagInputModule in /Users/avatsaev/DEV/ummah/WEB/frontend/admin.ummah-books.com.ng/node_modules/ng2-tag-input/dist/modules/ng2-tag-input.module.d.ts

**Comment by youneschaoui** [comment] 2017-02-27 12:59
same here

**Comment by gen4sp** [comment] 2017-02-27 18:26
same

**Comment by Gbuomprisco** [comment] 2017-02-27 20:45
Possibly related to https://github.com/angular/angular-cli/issues/3674

**Comment by Gbuomprisco** [comment] 2017-02-28 09:35
Will have a deeper look later this evening, but right now I have no clue what's up here :|

**Comment by z--aszlo** [comment] 2017-02-28 09:39
same here after an update, before it didn't had this problem.

**Comment by Gbuomprisco** [comment] 2017-02-28 09:40
just a note: the difference between 0.8.6 and 0.8.7 is just a dev-dependency update, so I am inclined to think that the issue is related to an update in the tooling

**Comment by avatsaev** [comment] 2017-02-28 09:44
I see that you are not using yarn to manage your dependencies, could you maybe lock your dependencies with yarn.lock, this will help to avoid a lot of issues in the future. https://yarnpkg.com/en/

**Comment by Gbuomprisco** [comment] 2017-02-28 09:46
Hi @avatsaev,

Yeah I'll consider that :). But the tooling issue in question is not in the repository, but in users' repositories.

**Comment by avatsaev** [comment] 2017-02-28 09:47
Yes, and I'm pretty sure Angular Team are at it again with their shenanigans on Angular CLI. But better investigate to be sure, I'll try to look into it too this evening.

**Comment by Gbuomprisco** [comment] 2017-02-28 09:51
very appreciated, thanks @avatsaev!

**Comment by AVatch** [comment] 2017-03-03 15:56
+1 here encountering the same issue - this project is awesome, but the angular cli requirements have become a big blocker right now :/

**Comment by Gbuomprisco** [comment] 2017-03-03 15:58
I know - sorry, things keep changing in Angular 2. I'll try sort things out this weekend (and likely the next one, and the next one, and so on :)

**Comment by Gbuomprisco** [comment] 2017-03-04 11:06
Hi everyone,

I released version 0.8.8. Can you check it works? It works for me, with angular-cli 1.0.0-beta.32.3. Fingers crossed.

**Comment by avatsaev** [comment] 2017-03-04 11:18
Just tried it, everything is green on my side, AOT compilation also works.

I'd wait for confirmations from others before closing to make sure that there are no side effects, but seems like it's working fine now, good job!

**Comment by AVatch** [comment] 2017-03-04 16:52
Works for me too ! thanks

**Comment by Gbuomprisco** [comment] 2017-03-06 09:02
closing :)

**Closed by Gbuomprisco** 2017-03-06 09:02 UTC
Labels: enhancement
